# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=22)),
                ('p_gender', models.CharField(choices=[('nan', '\u7537'), ('nv', '\u5973')], default='nan', max_length=10)),
                ('p_info', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=22)),
                ('t_info', models.TextField(max_length=4220)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Team'),
        ),
    ]
